/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package brickbreaker.menu;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.PrintWriter;

/**
 *
 * @author Cole
 */
public class menuScores extends javax.swing.JFrame {
    
    /**
     * Creates new form menuScores
     * @throws Exception 
     */
    public menuScores() throws Exception {
        
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        
        HighScore[] list;
        
        list = loadScores();
        stringScores(list);
        
    }
    
    /**
     * Creates new form menuScores
     * @param name 
     * @param totalScore
     * @throws Exception
     */
    public menuScores(String name, long totalScore) throws Exception {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        
        // Create the list of high scores
        HighScore[] list;
        
        // Load the scores from the text file
        // & add the existing score to the array
        list = loadScores();
        HighScore temp = new HighScore(name, totalScore);
        list[20] = temp;

        sortScores(list);
        saveScores(list);
        
        stringScores(list);
        
    }
    
    /** Holds the high score & the name */
    class HighScore {
        
        String name = "Player";
        long score = 0;
        
        /** Creates a new HighScore with the defined name and score */
        public HighScore(String name, long score) {
            
            this.name = name;
            this.score = score;
            
        }
        
        @Override
        public String toString() {
            
            return "" + this.name + " " + this.score;
            
        }
        
    }
    
    private void stringScores(HighScore[] x) {
        
        // Create a string with all of the high scores
        String y = "";
        for (int i = 0; i < 20; i++) { y = y + (i + 1) + ":\t\t" + x[i].name + "\t\t" + x[i].score + "\n"; } 
        
        // Add the string to the text area
        scoreArea.setText(y);
        
    }
    
    /**
     * Uses the insertion sorting method to sort the high scores from highest to lowest
     * @param x the array of High Scores to be sorted
     * @return the sorted array of High Scores
     */
    private HighScore[] sortScores(HighScore[] x) {
        
        for (int i = 1; i < x.length; i++) {
            
            HighScore next = x[i];
            // Find the insertion location while moving all larger elements up
            int j = i;
            while (j > 0 && x[j - 1].score < next.score)
            {
                
                x[j] = x[j - 1];
                j--;
                
            }
            // Insert the element
            x[j] = next;
            
        }
        return x;
        
    }
    
    /**
     * Load the high scores from the text file
     * @return the array of high scores loaded from the file
     * @throws Exception 
     */
    private HighScore[] loadScores() throws Exception {
        
        BufferedReader file = new BufferedReader(new FileReader("scores.txt"));
        HighScore[] x = new HighScore[21];
        String line;
        int i = 0;
        
        line = file.readLine();
        
        while (line != null)
        {
            
            // Split the loaded string around the space
            String[] split = line.split(" ");
            HighScore temp = new HighScore(split[0], (int)Long.parseLong(split[1]));
            x[i] = temp;
            
            // Read the next line
            line = file.readLine();
            i++;
            
        }
        
        return x;
        
    }
    
    /**
     * Save all loaded high scores to the text file
     * @param x
     * @throws Exception 
     */
    private static void saveScores(HighScore[] x) throws Exception {
        
        try (PrintWriter writer = new PrintWriter("scores.txt")) {
            String temp;
            
            for (int i = 0; i < 20; i++)
            {
                
                temp = x[i].toString();
                writer.print(temp + "\n");
                
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        quitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        scoreArea = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("High Scores");
        titleLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        scoreArea.setEditable(false);
        scoreArea.setColumns(20);
        scoreArea.setRows(5);
        scoreArea.setTabSize(4);
        jScrollPane2.setViewportView(scoreArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_quitButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton quitButton;
    private javax.swing.JTextArea scoreArea;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
